# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Miles to go before I sleep.
email: info@aa8y.co
description: > # this means to ignore newlines until "baseurl:"
  As I am in the process of learning Scala, most of
  my posts would be about it. I believe, it would be a great way for me to
  document what I learn.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aa8y.co" # the base hostname & protocol for your site
github_username: aa8y

# Build settings
markdown: kramdown
